### PR TITLE
Release 0.9.0 into Master

### PR DESCRIPTION
**Pull request by jmcreasman**
Features added:
* #87
* #67
* #66
* #47
* #15
* #13
* #6
* #4

Features to be moved to Overflow:
* #48
* #46
* #14

### CODE REVIEW

**Comment by jmcreasman** [comment]
https://tanks-for-waiting.firebaseapp.com/

**Comment by al-the-x** [comment]
Maybe consider a version number for the Django API: http://stackoverflow.com/questions/14590292/version-number-in-django-applications

**Comment by al-the-x** [comment]
* Container with a min / max width on the page?
* Start thinking about landing page content...
* Re-evaluate remaining effort for carry-over stories
  * Add "smaller than a small" tasks to this release
  * Add "bug" tasks to this release
* Mock presentation for next week...

**Comment by Shea-Wolfe** [comment]
* [ ] Coloring for tanks/targets
* [ ] Container min-max for tank.

**Pull request merged**
